DROP TABLE EBA_DEMO_APPR_EMP CASCADE CONSTRAINTS;
DROP TABLE EBA_DEMO_APPR_DEPT CASCADE CONSTRAINTS;
DROP TABLE EBA_DEMO_APPR_APPROVERS CASCADE CONSTRAINTS;
DROP PACKAGE EBA_DEMO_APPR;
DROP PACKAGE EBA_DEMO_APPR_DATA;